# This is a basic workflow to help you get started with Actions

name: WDIO-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      HEADLESS: ${{secrets.HEADLESS}}
      LOG_LEVEL: ${{secrets.LOG_LEVEL}}
      TEST_STD_USER: ${{secrets.TEST_STD_USER}}
      TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
      TEST_COM_ADMIN_USER: ${{secrets.TEST_COM_ADMIN_USER}}
      TEST_COM_ADMIN_PWD: ${{secrets.TEST_COM_ADMIN_PWD}}
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run test:smoke